# Generated by Django 5.2.2 on 2026-07-31 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_portfoliotracking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_allowed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'asset',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
                'db_table': 'asset_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'db_table': 'data_source',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='marketdata',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='market_data', to='api.asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='api.assettype'),
        ),
        migrations.CreateModel(
            name='AssetSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_symbol', models.CharField(max_length=50)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('is_primary', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='api.asset')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_links', to='api.datasource')),
            ],
            options={
                'verbose_name': 'Asset Source',
                'verbose_name_plural': 'Asset Sources',
                'db_table': 'asset_source',
                'unique_together': {('asset', 'data_source')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='data_sources',
            field=models.ManyToManyField(related_name='assets', through='api.AssetSource', to='api.datasource'),
        ),
        migrations.CreateModel(
            name='PortfolioTrackingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=8, max_digits=12)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_positions', to='api.asset')),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_positions', to='api.portfoliotracking')),
            ],
            options={
                'verbose_name': 'Portfolio Tracking Asset',
                'verbose_name_plural': 'Portfolio Tracking Assets',
                'db_table': 'portfolio_tracking_asset',
                'unique_together': {('tracking', 'asset')},
            },
        ),
    ]
