# Generated by Django 5.2.2 on 2026-07-31 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_asset_assettype_datasource_marketdata_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_holdings', to='api.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_holdings', to='api.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Asset',
                'verbose_name_plural': 'Portfolio Assets',
                'db_table': 'portfolio_asset',
                'unique_together': {('portfolio', 'asset')},
            },
        ),
    ]
