# Generated by Django 5.2.2 on 2026-07-31 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_portfolioasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='portfoliotracking',
            name='distribution',
        ),
    ]
