# Generated by Django 5.2.2 on 2026-08-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_seed_asset_catalog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketdata',
            unique_together={('date', 'asset')},
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
