# Generated by Django 5.2.2 on 2026-08-01 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_marketdata_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketdata',
            name='symbol',
        ),
    ]
