# Generated by Django 5.2.2 on 2026-08-05 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_prediction_steps_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_auto_optimization', models.BooleanField(default=False)),
                ('optimization_model', models.CharField(choices=[('markowitz', 'Markowitz'), ('gnosse', 'Gnosse')], default='gnosse', max_length=20)),
                ('update_frequency', models.PositiveIntegerField(default=5, help_text='Intervalo (em dias) entre rebalanceamentos automáticos.')),
                ('last_optimization_date', models.DateField(blank=True, null=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='api.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Config',
                'verbose_name_plural': 'Portfolio Configs',
                'db_table': 'portfolio_config',
            },
        ),
    ]
